### ISSUE TITLE
configure can't find input Makefile.in

### ISSUE THREAD

**Issue by orsoromeo** [snopt/snopt-interface#29] opened 2019-12-04 09:50 UTC
I am attempting to install this repo with the following procedure:
```
cd snop-interface
./autogen.sh
./configure
```
however, at this step, I get the following error:
![snopt-interface](https://user-images.githubusercontent.com/14978496/70131951-1b1e9900-167b-11ea-9d7a-3f1e7ffa2770.png)
So I get this `config.status: error: cannot find input file: `Makefile.in'` which means that canfigure can't find the Makefile.in file (even if this is actually located in the current directory!). Does anyone know how to fix this?

**Comment by gnowzil** [comment] 2019-12-04 22:28
The real issue is two lines above the last line.  I think this is a system error rather than an error with this package.  Can you try to make sure you have all the standard autoconf tools installed on your system? e.g.,
```
sudo apt-get install autotools-dev
sudo apt-get install autoconf
```

**Comment by orsoromeo** [comment] 2019-12-05 10:09
The autoconf tools seem to be fine on my machine as far as I see:
![snopt-int](https://user-images.githubusercontent.com/14978496/70225568-2dfe9f80-1747-11ea-98c7-5448885fc5f5.png)

**Comment by gnowzil** [comment] 2019-12-13 23:26
I'm still not sure why you're getting this error, but are you using the downloaded libraries from https://ccom.ucsd.edu/~optimizers?  If you link to the cpp libraries, you don't have to compile this interface because it has been incorporated into `libsnopt7_cpp`.

**Comment by gnowzil** [comment] 2020-01-14 22:23
Which Fortran compiler are you using?

I just ran into this issue in another setting and it was because of the compiler.  I can't see the top of the config.log, but I do see issues in the lines where it's checking for the Fortran compiler libraries and options.

**Comment by orsoromeo** [comment] 2020-01-15 13:14
I confirm I downloaded the libraries from https://ccom.ucsd.edu/~optimizers and I am now using the interface incorporated in `libsnopt7_cpp` without actually building its source code. 
As regards the compiler I am instead using libgfortran.so.4

**Comment by gnowzil** [comment] 2020-01-17 18:05
I'm going to close this for now.  If anyone else runs into this, I'm fairly certain this is caused by either a broken or "not found" Fortran compiler.  You should check your configure output for messages like this:

![fortran0](https://user-images.githubusercontent.com/9013998/72634982-9f1d9f00-3910-11ea-87c6-a57e3d42666a.png)
![fortran1](https://user-images.githubusercontent.com/9013998/72634990-a17ff900-3910-11ea-859c-573213b622cb.png)

**Closed by gnowzil** 2020-01-17 18:05 UTC
